#==========================================================================
# Makefile for ObTools::Action
#
# Copyright (c) 2013 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE    = lib
NAME    = ot-action
# No OBJS
HEADERS = ot-action.h
DEPENDS = gen mt

TESTS   = test-action
TESTLIB = -lgtest
TESTCMD = ./test-action

ROOT    = ../..
include $(ROOT)/build/std.mk
