#==========================================================================
# Makefile for all XMLMesh components
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = core otmp client superlibs server bindings
include ../build/dir.mk



