#==========================================================================
# Makefile for all XMLMesh CLI bindings
#
# Copyright (c) 2016 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = send receive
SUBS_MINGW = send
SUBS_MIPS = send

DEBIAN-NAME    = ot-xmlmesh-cli
DEBIAN-VERSION = 2.2.1
DEBIAN-REVISION = 1

RELEASEDIR = ../release
include ../../../build/dir.mk



