#!/bin/bash
#==========================================================================
# Build Debian package for ObTools XMLMesh command line utility
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

set -e
TARGARCH=$4

DEB_VERSION=$2-$3
PACKAGE=$1_$2-$3_${TARGARCH}.deb
SRC_DIR=`dirname $0`
DEB_DIR=/tmp/${PACKAGE}.$$
RELEASE_DIR=$SRC_DIR/../../release/

mkdir -p $DEB_DIR/DEBIAN
mkdir -p $DEB_DIR/usr/bin/

install -m 0644 $SRC_DIR/DEBIAN/control $DEB_DIR/DEBIAN/control

echo "Version: $DEB_VERSION" >> $DEB_DIR/DEBIAN/control
echo "Architecture: $TARGARCH" >> $DEB_DIR/DEBIAN/control

install -s -m 0755 send/xmlmesh-send $DEB_DIR/usr/bin/ot-xmlmesh-send
install -s -m 0755 receive/xmlmesh-receive $DEB_DIR/usr/bin/ot-xmlmesh-receive

if [ $CENTOS ]; then
  . $ROOT/build/Makerpm
else
  #Build debs
  fakeroot -- dpkg -b $DEB_DIR $PACKAGE
fi

# clean up
rm -rf $DEB_DIR
