#==========================================================================
# Makefile for ObTools ObCache complete model test
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

# Source XMI file
XMI=complete.xmi

# Include master makefile from above
include ../model.mk


