#==========================================================================
# Makefile for ObTools ObCache complete model test
#
# Copyright (c) 2008 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

# Source XMI file
XMI=complete.xmi

# Include master makefile from above
include ../model.mk


