#==========================================================================
# Makefile for ObTools XMI Tool Generator
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= exe
NAME   	= xmitoolgen
OBJS 	= xmitoolgen.o
DEPENDS = toolgen cppt xml text misc
CLEANCMD = $(MAKE) -C tests clean
TESTCMD = $(MAKE) -C ../tests test

ROOT    = ../..
include $(ROOT)/build/std.mk


