#==========================================================================
# Makefile for ObTools XMI Tool Generator
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= exe
NAME   	= xmitoolgen-cc
OBJS 	= xmitoolgen-cc.o
DEPENDS = cppt xml text
CLEANCMD = $(MAKE) -C tests clean
TESTCMD = $(MAKE) -C ../tests test

ROOT    = ../..
include $(ROOT)/build/std.mk


