#==========================================================================
# Makefile for ObTools::Daemon
#
# Copyright (c) 2009 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-daemon
HEADERS = ot-daemon.h
OBJS  	= shell.o
TESTS 	= test-daemon
TESTCMD	= ../test-daemon.sh
DEPENDS = misc net log mt text xml init file

ROOT    = ../..
include $(ROOT)/build/std.mk



