#==========================================================================
# Makefile for ObTools::Daemon
#
# Copyright (c) 2009 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-daemon
HEADERS = ot-daemon.h
OBJS  	= process.o
TESTS 	= test-daemon
TESTCMD	= ./test-daemon
DEPENDS = misc net log mt text xml init file

ROOT    = ../..
include $(ROOT)/build/std.mk



