#==========================================================================
# Makefile for ObTools Toolgen core library
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-toolgen
HEADERS = ot-toolgen.h
OBJS    = generator.o
DEPENDS = cppt xml text

ROOT    = ../..
include $(ROOT)/build/std.mk


