#==========================================================================
# Makefile for ObTools Toolgen core library
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-toolgen
HEADERS = ot-toolgen.h
OBJS    = generator.o
DEPENDS = cppt xml text

ROOT    = ../..
include $(ROOT)/build/std.mk


