#==========================================================================
# Makefile for ObTools ReGen
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

NAME   	= ot-regen
HEADERS = ot-regen.h
OBJS  	= mfile.o master.o regenbuf.o
TESTS 	= regen
TESTCMD	= ./regen foo.gen ../tests/example.h  && \
	  ./regen foo.gen ../tests/example.h

ROOT    = ../..
include $(ROOT)/build/lib.mk









