#==========================================================================
# Makefile for ObTools ReGen
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-regen
HEADERS = ot-regen.h
OBJS  	= mfile.o master.o regenbuf.o
TESTS 	= regen
TESTCMD	= ./regen foo.gen ../tests/example.h  && \
	  ./regen foo.gen ../tests/example.h

ROOT    = ../..
include $(ROOT)/build/std.mk









