#==========================================================================
# Makefile for ObTools::Text
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

NAME   	= ot-text
HEADERS = ot-text.h 
OBJS  	= ws.o pattern.o case.o 
TESTS 	= test-ws test-pattern test-case
TESTCMD	= ./test-ws && ./test-pattern && ./test-case
MULTI    = 1
VARIANT-SINGLE = 1

ROOT    = ../..
include $(ROOT)/build/lib.mk


