#==========================================================================
# Makefile for ObTools libraries release
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

all: 

clean:
	-@rm -f *.so *.so.* *.a *.h *.tgz *~ *.v *.deb
