#==========================================================================
# Makefile for ObTools libraries release
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
#==========================================================================

all: 
	-@rm *.tgz *~
	tar cvfz obtools-libs.tgz --exclude=CVS --exclude=Makefile *





