#==========================================================================
# Makefile for ObTools::Action
#
# Copyright (c) 2013 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE    = lib
NAME    = ot-alarm
OBJS    = alarm.o
HEADERS = ot-alarm.h
DEPENDS = mt time

TESTS   = test-alarm
TESTLIB = -lgtest
TESTCMD = ./test-alarm

ROOT    = ../..
include $(ROOT)/build/std.mk
