#==========================================================================
# Makefile for all ObTools ObCache parts
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

SUBS = storage memory
include ../build/dir.mk

