#==========================================================================
# Makefile for ObTools::SSL
#
# Copyright (c) 2008 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-ssl
HEADERS = ot-ssl.h
OBJS  	= context.o socket.o client.o server.o
TESTS 	= 
DEPENDS = mt net log xml text
TESTCMD	= 
SOCKET = 1

ROOT    = ../..
include $(ROOT)/build/std.mk

