#!/bin/sh
#==========================================================================
# Build Debian package for ObTools XMLMesh PHP extension
#
# Copyright (c) 2005 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

set -e

DEB_VERSION=$2-$3
PACKAGE=$1_$2-$3_i386.deb
SRC_DIR=`dirname $0`
DEB_DIR=/tmp/${PACKAGE}.$$

mkdir -p $DEB_DIR/DEBIAN
mkdir -p $DEB_DIR/usr/share/php

install -m 0644 $SRC_DIR/DEBIAN/control $DEB_DIR/DEBIAN/control
install -m 0644 $SRC_DIR/ot-xmlmesh.php $DEB_DIR/usr/share/php


echo "Version: $DEB_VERSION" >> $DEB_DIR/DEBIAN/control


fakeroot -- dpkg -b $DEB_DIR $PACKAGE
cp $PACKAGE $SRC_DIR/../../release/

# clean up
rm -rf $DEB_DIR
