#==========================================================================
# Makefile for ObTools XMLMesh PHP binding
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

NAME   	= php_xmlmesh_native

DEBIAN-NAME    = ot-xmlmesh-php-native
DEBIAN-VERSION = 0.2.1
DEBIAN-REVISION = 2
RELEASEDIR = ../../release

ROOT    = ../../..
include $(ROOT)/build/std.mk

