#==========================================================================
# Makefile for ObTools XMLMesh PHP binding
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

NAME   	= php_xmlmesh_native

DEBIAN-NAME    = ot-xmlmesh-php-native
DEBIAN-VERSION = 0.3.1
DEBIAN-REVISION = 2
RELEASEDIR = ../../release

TESTS = test-client
TESTCMD = phpunit ../test/test-ot-xmlmesh.php

ROOT    = ../../..
include $(ROOT)/build/std.mk

