#==========================================================================
# Makefile for ObTools XML Tool Generator
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= exe
NAME   	= xmltoolgen
OBJS 	= xmltoolgen.o
DEPENDS = toolgen cppt xml text misc
CLEANCMD = $(MAKE) -C tests clean
TESTCMD = $(MAKE) -C ../tests test

ROOT    = ../..
include $(ROOT)/build/std.mk




