#==========================================================================
# Makefile for ObTools tools release
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

all:


clean:



