#==========================================================================
# Makefile for ObTools::Huffman
#
# Copyright (c) 2011 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE    = lib
NAME    = ot-huffman
HEADERS = ot-huffman.h
DEPENDS = chan
OBJS    = tree.o
TESTS   = test-tree
TESTLIB = -lgtest
TESTCMD = ./test-tree

ROOT    = ../..
include $(ROOT)/build/std.mk
