#==========================================================================
# Makefile for ObTools::Hash
#
# Copyright (c) 2006 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-hash
# No OBJS
HEADERS = ot-hash.h
TESTS 	= test-hash
TESTCMD	= ./test-hash
MT-VARIANTS = 1

ifdef MULTI
DEPENDS = mt
endif

ROOT    = ../..
include $(ROOT)/build/std.mk



