#==========================================================================
# Makefile for ObTools::Hash
#
# Copyright (c) 2006 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-hash
# No OBJS
HEADERS = ot-hash.h
DEPENDS = mt
TESTS 	= test-hash
TESTCMD	= ./test-hash

ROOT    = ../..
include $(ROOT)/build/std.mk



