#==========================================================================
# Makefile for ObTools::Hash
#
# Copyright (c) 2006 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-hash
# No OBJS
HEADERS = ot-hash.h
DEPENDS = mt
TESTS 	= test-hash
TESTCMD	= ./test-hash

ROOT    = ../..
include $(ROOT)/build/std.mk



