#==========================================================================
# Makefile for angel test process
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= exe
NAME    = test-process
OBJS 	= test-process.o
MULTI   = 0

ROOT    = ../../..
include $(ROOT)/build/std.mk
