#==========================================================================
# Makefile for angel test process
#
# Copyright (c) 2005 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= exe
NAME    = test-process
OBJS 	= test-process.o
MULTI   = 0

ROOT    = ../../..
include $(ROOT)/build/std.mk
