#==========================================================================
# Makefile for ObTools XMLMesh release
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

all: 
	-@rm *.tgz *~
	tar cvfz obtools-xmlmesh.tgz --exclude=CVS --exclude=Makefile *

clean:
	-@rm -f *.a *.h *.tgz *~





