#==========================================================================
# Makefile for ObTools XMLMesh release
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
#==========================================================================

all: 
	-@rm *.tgz *~
	tar cvfz obtools-xmlmesh.tgz --exclude=CVS --exclude=Makefile *





