#==========================================================================
# Makefile for ObTools::Message
#
# Copyright (c) 2010 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-msg
HEADERS = ot-msg.h
OBJS  	= broker.o 
DEPENDS = log xml init ssl
TESTS 	= 
TESTCMD	= 
SOCKET = 1

ROOT    = ../..
include $(ROOT)/build/std.mk

