#==========================================================================
# Makefile for ObTools Code generation super library
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= superlib
NAME	= ot-codegen
VERSION	= 1.0.0
DEPENDS = cppt regen xmi
MULTI	= 1

DEBIAN-NAME    = libot-codegen
DEBIAN-VERSION = $(VERSION)
DEBIAN-REVISION = 2

ROOT	= ../../..
include $(ROOT)/build/std.mk
