#==========================================================================
# Makefile for ObTools::MT
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

NAME   	= ot-mt
HEADERS = ot-mt.h
OBJS  	= thread.o pool.o
TESTS 	= test-thread test-pool test-queue test-mutex test-rmutex
TESTCMD	= ./test-thread 10 && ./test-queue
MULTI    = 1

ROOT    = ../..
include $(ROOT)/build/lib.mk




