#==========================================================================
# Makefile for ObTools::Init
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-init
HEADERS = ot-init.h
OBJS  	= init.o
DEPENDS = xml
TESTS 	= test-init
TESTCMD	= ./test-init

ROOT    = ../..
include $(ROOT)/build/std.mk

