#==========================================================================
# Makefile for ObTools::Init
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-init
HEADERS = ot-init.h
OBJS  	= init.o
DEPENDS = xml
TESTS 	= test-init
TESTCMD	= ./test-init

ROOT    = ../..
include $(ROOT)/build/std.mk

