#==========================================================================
# Makefile for ObTools ObCache SQL library
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-obcache-sql
HEADERS = ot-obcache-sql.h
OBJS    = storage.o
DEPENDS = obcache-core db xml net log misc mt

ROOT    = ../../..
include $(ROOT)/build/std.mk


