#==========================================================================
# Makefile for ObTools ObCache SQL library
#
# Copyright (c) 2008 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-obcache-sql
HEADERS = ot-obcache-sql.h
OBJS    = storage.o
DEPENDS = obcache-core db xml net log misc mt

ROOT    = ../../..
include $(ROOT)/build/std.mk


