#==========================================================================
# Makefile for all ObTools ObCache libraries
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

SUBS = core sql
include ../../build/dir.mk

