#==========================================================================
# Makefile for all ObTools ObCache libraries
#
# Copyright (c) 2008 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = core sql
NORELEASE=1
include ../../build/dir.mk

