#!/bin/sh
#==========================================================================
# Build Debian package for angeld process manager
#
# Copyright (c) 2005 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

set -e

DEB_VERSION=$2-$3
TARGARCH=$4
PACKAGE=$1_$2-$3_${TARGARCH}.deb
SRC_DIR=`dirname $0`
DEB_DIR=/tmp/${PACKAGE}.$$
RELEASE_DIR=$SRC_DIR/../release/

mkdir -p $DEB_DIR/DEBIAN
mkdir -p $DEB_DIR/usr/sbin
mkdir -p $DEB_DIR/etc/angel/processes
mkdir -p $DEB_DIR/var/log/angel

install -m 0644 $SRC_DIR/DEBIAN/control $DEB_DIR/DEBIAN/control
install -m 0644 $SRC_DIR/DEBIAN/conffiles $DEB_DIR/DEBIAN/conffiles
install -m 0755 $SRC_DIR/DEBIAN/postinst $DEB_DIR/DEBIAN/postinst
install -m 0755 $SRC_DIR/DEBIAN/prerm $DEB_DIR/DEBIAN/prerm

echo "Version: $DEB_VERSION" >> $DEB_DIR/DEBIAN/control
echo "Architecture: $TARGARCH" >> $DEB_DIR/DEBIAN/control

install -s -m 0755 angeld $DEB_DIR/usr/sbin/angeld
install -m 0644 $SRC_DIR/angeld.cfg.xml $DEB_DIR/etc/angel/angeld.cfg.xml

if [ $CENTOS ]; then
    RPM_CONFIGDIR=/etc/angel
    RPM_SERVICE=1
    . $ROOT/build/Makerpm
else
  #Build debs
  fakeroot -- dpkg -b $DEB_DIR $PACKAGE
  cp $PACKAGE $SRC_DIR/../release/
fi

# clean up
rm -rf $DEB_DIR
