#==========================================================================
# Makefile for ObTools ObCache simple model test
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

# XMI source file
XMI=simple.xmi

# Include master makefile from above
include ../model.mk


