#==========================================================================
# Makefile for ObTools ObCache simple model test
#
# Copyright (c) 2008 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

# XMI source file
XMI=simple.xmi

# Include master makefile from above
include ../model.mk


