#==========================================================================
# Makefile for ObTools ObCache simple model test
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

# Name of model
MODEL=simple

# Include master makefile from above
include ../model.mk


