#==========================================================================
# Makefile for ObTools::DB - generic database support
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME    = ot-db
HEADERS = ot-db.h
OBJS  	= connection.o row.o transaction.o pool.o
DEPENDS = log text time mt

ROOT    = ../..
include $(ROOT)/build/std.mk





