#==========================================================================
# Makefile for all XMLMesh language bindings
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = php cli
SUBS_MINGW = cli
SUBS_MIPS = cli

RELEASEDIR = ../release
include ../../build/dir.mk



