#==========================================================================
# Makefile for all XMLMesh language bindings
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

SUBS = c php cli
SUBS_MINGW = c cli
SUBS_MIPS = c cli

RELEASEDIR = ../release
include ../../build/dir.mk



