#==========================================================================
# Makefile for ObTools Angel release
#
# Copyright (c) 2005 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

all:

clean:
	-@rm -f *.so *.so.* *.a *.h *.tgz *.cfg.xml \
	angeld angel *.deb *.v *~





