#==========================================================================
# Makefile for ObTools Angel release
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

all:

clean:
	-@rm -f *.so *.so.* *.a *.h *.tgz *.cfg.xml \
	angeld angel *.deb *.v *~





