#==========================================================================
# Makefile for ObTools::Cache
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-cache
# No OBJS
HEADERS = ot-cache.h
DEPENDS = mt
TESTS 	= test-timeout-use test-timeout-age test-pointer
TESTCMD	= ./test-pointer

ROOT    = ../..
include $(ROOT)/build/std.mk



