#==========================================================================
# Makefile for ObTools::Log
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-log
HEADERS = ot-log.h
OBJS  	= distributor.o filter.o logstream.o channel.o logger.o
DEPENDS = text time mt
TESTS 	= test-log
TESTCMD	= ./test-log
MT-VARIANTS = 1

ROOT    = ../..
include $(ROOT)/build/std.mk




