#==========================================================================
# Top-level Makefile for Angel process manager
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = angeld cli
include ../build/dir.mk



