#==========================================================================
# Top-level Makefile for Angel process manager
#
# Copyright (c) 2005 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

SUBS = angeld cli
include ../build/dir.mk



