#!/bin/bash
#==========================================================================
# Build Debian package for angel command line utility
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

set -e

DEB_VERSION=$2-$3
TARGARCH=$4
PACKAGE=$1_$2-$3_${TARGARCH}.deb
SRC_DIR=`dirname $0`
DEB_DIR=/tmp/${PACKAGE}.$$
RELEASE_DIR=$SRC_DIR/../release/

mkdir -p $DEB_DIR/DEBIAN
mkdir -p $DEB_DIR/usr/sbin
mkdir -p $DEB_DIR/etc/angel/

install -m 0644 $SRC_DIR/DEBIAN/control $DEB_DIR/DEBIAN/control
install -m 0644 $SRC_DIR/DEBIAN/conffiles $DEB_DIR/DEBIAN/conffiles

echo "Version: $DEB_VERSION" >> $DEB_DIR/DEBIAN/control
echo "Architecture: $TARGARCH" >> $DEB_DIR/DEBIAN/control

install -s -m 0755 angel $DEB_DIR/usr/sbin/angel
install -m 0644 $SRC_DIR/angel.cfg.xml $DEB_DIR/etc/angel/angel.cfg.xml

if [ $CENTOS ]; then
  . $ROOT/build/Makerpm
else
  #Build debs
  fakeroot -- dpkg -b $DEB_DIR $PACKAGE
  cp $PACKAGE $SRC_DIR/../release/
fi

# clean up
rm -rf $DEB_DIR
