#==========================================================================
# Makefile for all ObTools ObCache tests
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

SUBS = simple complete
NORELEASE=1
include ../../build/dir.mk

