#==========================================================================
# Makefile for all ObTools XMLMesh super-libraries
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = xmlmesh
RELEASEDIR = ../release
include ../../build/dir.mk


