#==========================================================================
# Makefile for all ObTools XMLMesh super-libraries
#
# Copyright (c) 2005 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

SUBS = xmlmesh
RELEASEDIR = ../release
include ../../build/dir.mk


