#==========================================================================
# Makefile for Angel tests
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = test-process
include ../../build/dir.mk



