#==========================================================================
# Makefile for Angel tests
#
# Copyright (c) 2005 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

SUBS = test-process
include ../../build/dir.mk



