#==========================================================================
# Makefile for ObTools::Tube
#
# Copyright (c) 2007 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-tube
HEADERS = ot-tube.h
OBJS  	= server.o client.o
TESTS 	= test-server test-client
TESTCMD	= 
DEPENDS = misc net log mt chan
SOCKET  = 1

ROOT    = ../..
include $(ROOT)/build/std.mk



