#==========================================================================
# Makefile for ObTools Postgres Database super library
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= superlib
NAME   	= ot-db-pgsql
VERSION	= 1.0.0
DEPENDS = db-pgsql
MT-VARIANTS = 1

ROOT    = ../../..
include $(ROOT)/build/std.mk


