#!/bin/bash
set -e

#Insert /usr/lib/obtools in ld.so.conf
if ! grep -qs ^/usr/lib/obtools\$ /etc/ld.so.conf; then
  echo /usr/lib/obtools >> /etc/ld.so.conf
fi

if [ "\$1" = "configure" ]; then
    ldconfig
fi

