#==========================================================================
# Makefile for all ObTools super-libraries
#
# Copyright (c) 2003 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

RELEASEDIR = ../release
SUBS = general db db-pgsql db-mysql codegen
include ../../build/dir.mk
