#==========================================================================
# Makefile for all ObTools super-libraries
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

RELEASEDIR = ../release
SUBS = general db db-pgsql db-mysql codegen
SUBS_MINGW = general
SUBS_MIPS = general

include ../../build/dir.mk
