#==========================================================================
# Makefile for ObTools::Ring
#
# Copyright (c) 2010 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-ring
# No OBJS
HEADERS = ot-ring.h
DEPENDS = mt
TESTS 	= test-ring test-ring-gtest
TESTLIB = -lgtest
TESTCMD	= ./test-ring-gtest && ./test-ring

ROOT    = ../..
include $(ROOT)/build/std.mk



