#==========================================================================
# Makefile for all ObTools tools
#
# Copyright (c) 2003 Object Toolsmiths Limited.  All rights reserved
#==========================================================================

all: 
	$(MAKE) -C xmltools

clean: 
	-@rm -f *~
	$(MAKE) -C xmltools clean

test: 
	$(MAKE) -C xmltools test



