#==========================================================================
# Makefile for all ObTools tools
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

SUBS = toolgen xmltoolgen xmitoolgen obdoc
include ../build/dir.mk

