#==========================================================================
# Makefile for ObTools ObCache core library
#
# Copyright (c) 2008 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-obcache-core
HEADERS = ot-obcache.h
OBJS    = 
DEPENDS = cache

ROOT    = ../../..
include $(ROOT)/build/std.mk


