#==========================================================================
# Makefile for ObTools ObCache core library
#
# Copyright (c) 2008 xMill Consulting Limited.  All rights reserved
# @@@ MASTER SOURCE - PROPRIETARY AND CONFIDENTIAL - NO LICENCE GRANTED
#==========================================================================

TYPE	= lib
NAME   	= ot-obcache-core
HEADERS = ot-obcache.h
OBJS    = 
DEPENDS = cache

ROOT    = ../..
include $(ROOT)/build/std.mk


