#!/bin/sh
#==========================================================================
# Build Debian package for ObTools XMLMesh PHP extension
#
# Copyright (c) 2005 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

set -e
TARGARCH=$4

DEB_VERSION=$2-$3
PACKAGE=$1_$2-$3_${TARGARCH}.deb
SRC_DIR=`dirname $0`
DEB_DIR=/tmp/${PACKAGE}.$$

mkdir -p $DEB_DIR/DEBIAN
mkdir -p $DEB_DIR/usr/lib/php5/20060613+lfs/

#mkdir -p $DEB_DIR/usr/lib/php4/20020429/
#mkdir -p $DEB_DIR/usr/lib/php4/20050606/

install -m 0644 $SRC_DIR/DEBIAN/control $DEB_DIR/DEBIAN/control
install -m 0755 $SRC_DIR/DEBIAN/postinst $DEB_DIR/DEBIAN/postinst
install -m 0755 $SRC_DIR/DEBIAN/prerm $DEB_DIR/DEBIAN/prerm

echo "Version: $DEB_VERSION" >> $DEB_DIR/DEBIAN/control
echo "Architecture: $TARGARCH" >> $DEB_DIR/DEBIAN/control

#Not sure if we're supposed to provide the same thing twice!
#install -s -m 0755 php_xmlmesh.so $DEB_DIR/usr/lib/php4/20020429/
install -s -m 0755 php_xmlmesh.so  $DEB_DIR/usr/lib/php5/20060613+lfs

#!!! We're not - if we install it in the other directory we need to 
# change the API version.
#install -s -m 0755 php_xmlmesh.so $DEB_DIR/usr/lib/php4/20050606/
if [ $CENTOS ]; then
    . $ROOT/build/Makerpm
else
  #Build debs
  fakeroot -- dpkg -b $DEB_DIR $PACKAGE
  cp $PACKAGE $SRC_DIR/../../release/
fi

# clean up
rm -rf $DEB_DIR
