#!/bin/bash
set -e

#Ensure we're registered in the INI files
if [ -f /etc/php4/apache/php.ini ]; then
if ! grep -qs ^extension=php_xmlmesh.so\$ /etc/php4/apache/php.ini; then
  echo "Adding extension=php_xmlmesh.so to /etc/php4/apache/php.ini";
  echo extension=php_xmlmesh.so >> /etc/php4/apache/php.ini;
fi
fi

if [ -f /etc/php4/cgi/php.ini ]; then
if ! grep -qs ^extension=php_xmlmesh.so\$ /etc/php4/cgi/php.ini; then
  echo "Adding extension=php_xmlmesh.so to /etc/php4/cgi/php.ini";
  echo extension=php_xmlmesh.so >> /etc/php4/cgi/php.ini;
fi
fi

if [ -f /etc/php4/cli/php.ini ]; then
if ! grep -qs ^extension=php_xmlmesh.so\$ /etc/php4/cli/php.ini; then
  echo "Adding extension=php_xmlmesh.so to /etc/php4/cli/php.ini";
  echo extension=php_xmlmesh.so >> /etc/php4/cli/php.ini;
fi
fi

