#!/bin/bash
set -e


if [ $1 = "remove" -o $1 = "purge" ]; then
#Remove from PHP ini files
    echo "Removing extension=php_xmlmesh.so from /etc/php4/apache/php.ini";
    grep -vs ^extension=php_xmlmesh.so\$ /etc/php4/apache/php.ini > /etc/php4/apache/php.ini.new
    mv /etc/php4/apache/php.ini.new /etc/php4/apache/php.ini

    echo "Removing extension=php_xmlmesh.so from /etc/php4/cgi/php.ini";
    grep -vs ^extension=php_xmlmesh.so\$ /etc/php4/cgi/php.ini > /etc/php4/cgi/php.ini.new
    mv /etc/php4/cgi/php.ini.new /etc/php4/cgi/php.ini

    echo "Removing extension=php_xmlmesh.so from /etc/php4/cli/php.ini";
    grep -vs ^extension=php_xmlmesh.so\$ /etc/php4/cli/php.ini > /etc/php4/cli/php.ini.new
    mv /etc/php4/cli/php.ini.new /etc/php4/cli/php.ini

fi

