#==========================================================================
# Makefile for ObTools::Gather
#
# Copyright (c) 2010 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-gather
OBJS    = buffer.o
HEADERS = ot-gather.h
DEPENDS = misc chan

TESTS 	= test-gather
TESTLIB = -lgtest
TESTCMD	= ./test-gather

ROOT    = ../..
include $(ROOT)/build/std.mk



