#==========================================================================
# Makefile for ObTools::Lex
#
# Copyright (c) 2016 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE    = lib
NAME    = ot-lex
HEADERS = ot-lex.h
DEPENDS = text misc
OBJS    = analyser.o
TESTS   = test-analyser
TESTLIB = -lgtest
TESTCMD = ./test-analyser

ROOT    = ../..
include $(ROOT)/build/std.mk
