#==========================================================================
# Makefile for AMF library
#
# Copyright (c) 2012 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-amf
HEADERS = ot-amf.h
OBJS  	= value.o
DEPENDS = text misc time
TESTS 	= test-value
TESTLIB = -lgtest
TESTCMD	= ./test-value

ROOT    = ../..
include $(ROOT)/build/std.mk



