#==========================================================================
# Makefile for ObTools::Expression
#
# Copyright (c) 2013 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE    = lib
NAME    = ot-expr
HEADERS = ot-expr.h
DEPENDS = text
OBJS    = token.o
TESTS   = test-token
TESTLIB = -lgtest
TESTCMD = ./test-token

ROOT    = ../..
include $(ROOT)/build/std.mk
