#==========================================================================
# Makefile for ObTools XMLMesh core library
#
# Copyright (c) 2003 Paul Clark.  All rights reserved
# This code comes with NO WARRANTY and is subject to licence agreement
#==========================================================================

TYPE	= lib
NAME   	= ot-xmlmesh-core
HEADERS = ot-xmlmesh.h
OBJS    = message.o m-fault.o m-subscription.o
DEPENDS = soap web xml net log misc mt

ROOT    = ../..
include $(ROOT)/build/std.mk


